version: '3'
services:
  db:
    image: mysql:8.0.37
    volumes:
      - ./municipios.sql:/docker-entrypoint-initdb.d/municipios.sql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "municipios"
    networks:
      - wpsite

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      FLASK_APP: "app.py"
      FLASK_ENV: "development"
      MYSQL_HOST: "db"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "1234"
      MYSQL_DB: "municipios"
    depends_on:
      - db
    networks:
      - wpsite
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: "db"
      PMA_USER: "root"
      PMA_PASSWORD: "1234"
    networks:
      - wpsite

networks:
  wpsite:
