FROM php:8.0.0-apache


# FROM wordpress:latest

# # Copiar tu código editado al directorio de WordPress dentro del contenedor
# COPY ./wordpress/ /var/www/html/

# # Exponer el puerto en el que se ejecuta WordPress (normalmente 80)
# EXPOSE 80

# # Comando para iniciar WordPress
# CMD ["apache2-foreground"]